import json
import time
import requests
from pathlib import Path
from typing import List, Dict, Any
from .environment_params import EnvironmentConfig
from ..utils.logger import LoggerSetup



"""

    Desc: This Module Provides A WebODM Client Interface For API Access For Environment-Specific
    Point Cloud Generation. The Module Utilizes A Configuration Loader To Load
    Point Cloud Configuration Parameters. The WebODM Client Utilizes A Session
    To Communicate With The WebODM API And Generate Point Clouds. The Client
    Utilizes JWT Token Authentication For Security. The Client Also Utilizes
    Environment Configuration To Generate Point Clouds With Specific Parameters.

"""
class WebODMClient:
    
    """
    
        Desc: Initializes Our WebODM Client With A Config Loader (config_loader)
        To Load Point Cloud Configuration Parameters. The Client Utilizes A Logger
        To Write Logs. The Client Also Initializes Our WebODM API Base URL
        And Session For API Communication. The Client Also Utilizes JWT Token
        Authentication For Security.

        Preconditions:
            1. config_loader: ConfigLoader Object

        Postconditions:
            1. Set Our logger 
            2. Load Point Cloud Configuration Parameters
            3. Initialize WebODM API Base URL
            4. Initialize Session For API Communication
            5. Utilize JWT Token Authentication
    
    """
    def __init__(self, config_loader):
        self.logger = LoggerSetup(__name__).get_logger()
        self.config = config_loader.get_point_cloud_config()
        self.base_url = f"http://{self.config['webodm']['host']}:{self.config['webodm']['port']}"
        self.session = requests.Session()
        
        # Should Use JWT Token Authentication Instead Of Basic Auth
        self.api_key = self._get_token()
        self.session.headers.update({'Authorization': f'JWT {self.api_key}'})
        

    """
    
        Desc: This Function Utilizes Our base_url As Well As config To
        Authenticate Our WebODM Client. The Function Returns A JWT Token Header
        For Authentication For API Calls.

        Preconditions:
            1. base_url: WebODM API Base URL
            2. config: Point Cloud Configuration Parameters

        Postconditions:
            1. Authenticate WebODM Client
            2. Return JWT Token Header For Authentication
    
    """
    def _get_token(self):
        # Ask WebODM For A Token
        response = requests.post(f"{self.base_url}/api/token-auth/",
                               data={
                                   'username': self.config['webodm']['username'],
                                   'password': self.config['webodm']['password']
                               })
        
        # Look For Token In Response
        response.raise_for_status()
        return response.json()['token']
    

    """
    
        Desc: This Function Cleans Up All Projects In WebODM With The "Generated By ResilientGeoDrone" Descriptor.
        The Function Removes All Projects Generated By ResilientGeoDrone. The Function
        Returns True If All Projects Are Cleaned Up And False Otherwise. 

        Preconditions:
            1. base_url: WebODM API Base URL
        
        Postconditions:
            1. Remove All Projects With Description Of "Generated By ResilientGeoDrone"
            2. Return True If All Projects Are Cleaned Up And False Otherwise
    
    """
    def _cleanup_projects(self) -> None:
        # Grab All Our Projects
        response = self.session.get(f"{self.base_url}/api/projects/")
        response.raise_for_status()
        
        # Loop Through Projects To Find Non-ResilientGeoDrone Ones
        for project in response.json():
            project_id = project['id']
            if project['description'] == "Generated by ResilientGeoDrone":
                response = self.session.delete(f"{self.base_url}/api/projects/{project_id}/")
                response.raise_for_status()

        # Grab Our Projects Again
        response = self.session.get(f"{self.base_url}/api/projects/")
        response.raise_for_status()
        
         # Loop Through And Look To Ensure All Projects Are Cleaned Up
        for project in response.json():
            if project['description'] == "Generated by ResilientGeoDrone":
                return False
        
        return True


    """
    
        Desc: This Function Generates A Point Cloud With Environment-Specific
        Parameters From A Specified Image-Set (image_paths). The Function Utilizes
        Environment Configuration (environment) To Generate Point Clouds With Specific
        Parameters. The Function Returns The Point Cloud As A Dictionary.

        Preconditions:
            1. image_paths: List Of Image Paths
            2. environment: Environment Configuration Type
            3. image_paths And environment Must Be Valid

        Postconditions:
            1. Generate Point Cloud With Environment-Specific Parameters
            2. Return Point Cloud As A Dictionary
    
    """
    def generate_point_cloud(self, image_paths: List[Path], environment: str) -> Dict[str, Any]:
        # Attempt To Generate Point Cloud
        try:
            # Get Environment Conditions From Our YAML
            env_config = EnvironmentConfig.get_environment(environment)
            if not env_config:
                raise ValueError(f"Invalid environment type: {environment}")

            # Create A Project
            project_id = self._create_project()
            
            # Create A Task With Environment-Specific Parameters
            task_data = {
                'name': f"Task_{int(time.time())}",
                'auto_processing': 'true',
                'options': json.dumps(env_config.to_webodm_options())
            }

            # Upload Images To Create A New Task
            files = [('images', (path.name, open(path, 'rb'), 'image/jpeg')) 
                    for path in image_paths]
            
            response = self.session.post(
                f"{self.base_url}/api/projects/{project_id}/tasks/",
                files=files
            )
            response.raise_for_status()

            # Get Task ID
            self.task_id = response.json()['id']

            # Wait For Our Generation To Complete
            return self._wait_for_completion(self.task_id, project_id)
        # If Generation Fails, Log Error And Raise Exception
        except Exception as e:
            self.logger.error(f"Point cloud generation failed: {str(e)}")
            raise


    """
    
        Desc: This Function Creates A New WebODM Project. The Function
        Generates A Unique Name For The Project Using A Timestamp. The
        Function Returns The Project ID As An Integer.

        Preconditions:
            1. base_url: WebODM API Base URL
        
        Postconditions:
            1. Create New WebODM Project With Description "Generated By ResilientGeoDrone"
            2. Return Project ID As An Integer
    
    """
    def _create_project(self) -> int:
        # Create A New Project
        project_data = {
            "name": f"Project_{int(time.time())}",  # Generate Unique Name Using Timestamp
            "description": "Generated by ResilientGeoDrone"  # Description For Our Project
        }
        
        # Pass Over Our Project To WebODM For Creation
        response = self.session.post(
            f"{self.base_url}/api/projects/",
            json=project_data
        )
        
        # Check Status Of Project Creation
        try:
            response.raise_for_status()
        # If Project Creation Fails, Log Error And Raise Exception
        except requests.exceptions.HTTPError as e:
            self.logger.error(f"Failed to create project: {response.text}")
            raise

        # Return Project ID If Successful
        return response.json()['id']
    

    """
    
        Desc: This Function Tests The WebODM Connection. The Function
        Sends A GET Request To The WebODM API To Test The Connection.
        The Function Returns True If The Connection Is Successful And
        False Otherwise.

        Preconditions:
            1. base_url: WebODM API Base URL

        Postconditions:
            1. Test WebODM Connection
            2. Return True If Connection Is Successful And False Otherwise
    
    """
    def _test_connection(self) -> bool:
        # Test Connection To WebODM By Getting API
        response = self.session.get(f"{self.base_url}/api/")
        return response.ok


    """
    
        Desc: This Function Uploads Images (Provided In image_paths) To Create
        A New Task On A Given Project, project_id. The Function Initializes A New
        Task And Uploads Images In Chunks. The Function Commits The Task And 
        Returns The Task ID As A String.

        Preconditions:
            1. project_id: Project ID As An Integer
            2. image_paths: List Of Image Paths
            3. project_id And image_paths Must Be Valid

        Postconditions:
            1. Upload Images To Create A New Task
            2. Return Task ID As A String
    
    """
    def _upload_images(self, project_id: int, image_paths: List[Path]) -> str:
        # Attempt To Upload Images
        try:
            # Initialize A New Task
            init_response = self.session.post(
                f"{self.base_url}/api/task/new/init",
                data={
                    "name": f"Task_{int(time.time())}",
                    "options": json.dumps([
                        {"name": "dsm", "value": True},
                        {"name": "dtm", "value": True},
                        {"name": "pc-quality", "value": "high"},
                        {"name": "feature-quality", "value": "high"}
                    ])
                }
            )
            init_response.raise_for_status()
            # Get Task ID
            task_id = init_response.json()['uuid']

            # Upload Images In Chunks
            for path in image_paths:
                if path.exists() and path.is_file():
                    with open(path, 'rb') as f:
                        upload_response = self.session.post(
                            f"{self.base_url}/api/task/new/upload/{task_id}",
                            files={'images': (path.name, f, 'image/jpeg')}
                        )
                        upload_response.raise_for_status()

            # Commit The Task After Image Upload
            commit_response = self.session.post(
                f"{self.base_url}/api/task/new/commit/{task_id}"
            )
            commit_response.raise_for_status()
            
            # Return Task ID If Successful
            return task_id
        # If Image Upload Fails, Log Error And Raise Exception
        except requests.exceptions.HTTPError as e:
            self.logger.error(f"Failed to upload images: {e.response.text if hasattr(e, 'response') else str(e)}")
            raise


    """
    
        Desc: This Function Waits For Task Completion And Returns Results On The Task, task_id;
        On A Given Project, project_id. The Function Waits For The Task To Complete And Returns
        The Results. The Function Returns The Results As A Dictionary.

        Preconditions:
            1. task_id: Task ID As A String
            2. project_id: Project ID As An Integer
            3. task_id And project_id Must Be Valid
            4. task_id And project_id Must Relate To The Same Project

        Postconditions:
            1. Wait For Task Completion And Return Results
            2. Return Results As A Dictionary
    
    """
    def _wait_for_completion(self, task_id: str, project_id) -> Dict[str, Any]:
        # Lazy Loop To Wait For Task Completion
        while True:
            # Get Task Status
            response = self.session.get(
                f"{self.base_url}/api/projects/{project_id}/tasks/{task_id}/")
            response.raise_for_status()
            
            responseJson = response.json()
            status = responseJson['status']

            # Check Task Status
            print(f"Generating Model: {responseJson['running_progress'] * 100.0}%")
            if status == 40:  # COMPLETED
                return self._get_results(task_id)
            elif status in [30, 50]:  # FAILED or CANCELED
                raise Exception(f"Task failed or was canceled")
            
            # Wait For 15 Seconds Before Checking Again
            time.sleep(15)


    """
    
        Desc: This Function Gets Processing Results On A Given Task, task_id.
        The Function Returns The Processing Results As A Dictionary.

        Preconditions:
            1. task_id: Task ID As A String
        
        Postconditions:
            1. Get Processing Results
            2. Return Processing Results As A Dictionary
    
    """
    def _get_results(self, task_id: str) -> Dict[str, Any]:
        return {
            'all': f"{self.base_url}/api/task/{task_id}/download/all.zip",
            'images': f"{self.base_url}/api/task/{task_id}/download/images.zip",
            'point_cloud': f"{self.base_url}/api/task/{task_id}/download/georeferenced_model.laz",
            'orthophoto': f"{self.base_url}/api/task/{task_id}/download/orthophoto.tif",
            'dsm': f"{self.base_url}/api/task/{task_id}/download/dsm.tif",
            'dtm': f"{self.base_url}/api/task/{task_id}/download/dtm.tif"
        }


    """
    
        Desc: This Function Configures A Task With Environment-Specific Parameters
        On A Given Task, task_id. The Function Configures The Task With Environment-Specific
        Parameters. The Function Returns None.

        Preconditions:
            1. task_id: Task ID As An Integer
            2. env_config: Environment Configuration Type

        Postconditions:
            1. Configure Task With Environment-Specific Parameters
            2. Return None
    
    """
    def _configure_task(self, task_id: int, env_config: EnvironmentConfig) -> None:
        # Configure Task With Environment-Specific Parameters
        response = self.session.patch(
            f"{self.base_url}/api/projects/tasks/{task_id}/commit/",
            json=env_config.to_webodm_options()
        )
        response.raise_for_status()


    """
    
        Desc: This Function Processes A Task, task_id, And Returns Results.
        The Function Processes The Task And Returns Results As A Dictionary.

        Preconditions:
            1. task_id: Task ID As An Integer

        Postconditions:
            1. Process Task And Return Results
            2. Return Results As A Dictionary
    
    """
    def _process_task(self, task_id: int) -> Dict[str, Any]:
        # Process Task And Return Results
        response = self.session.post(f"{self.base_url}/api/tasks/{task_id}/commit/")
        response.raise_for_status()
        return self._wait_for_completion(task_id)
    

    """
    
        Desc: This Function Cleans Up All Projects In WebODM With The "Generated By ResilientGeoDrone" Descriptor.
        The Function Removes All Projects Generated By ResilientGeoDrone. The Function Returns True If
        All Projects Are Cleaned Up And False Otherwise. It Also Closes Out Our Session Used To Talk to WebODM API.

        Preconditions:
            1. None

        Postconditions:
            1. Remove All Projects With Description Of "Generated By ResilientGeoDrone"
            2. Return True If All Projects Are Cleaned Up And False Otherwise
            3. Close Out Session Used To Talk To WebODM API
    
    """
    def __del__(self):
        # Cleanup, Then Close Session
        self._cleanup_projects()
        self.session.close()